[package]
name = "step-merger"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-error = "2.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
utf8-chars = "3.0.2"
winnow = "0.6.8"
circular = "0.3.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ref_iter"
harness = false
